device: cuda:0  # can infer using only 1 gpu
verbose: True  # whether print statistics or not

checkpoints: './lightning_logs/version_11/checkpoints/epoch=5.ckpt'  # path to pl checkpoint

image_size: 224  # size of input image

with_labels: True  # Whether your csv file has labels or not
num_workers: 5  # param for infer dataloader
batch_size: 16  # batch size for infer dataloader

# uncomment this, to use online face cropping
# however it is not recommended
# you can only use cpu device as device for face-cropping nn
#face_detector:
#  image_size: 512
#  margin: 100
#  min_face_size: 100
#  thresholds: [0.6, 0.7, 0.7]
#  factor: 0.709
#  device: *device

root: '/data/project/rw/kakaopay/preprocess/kp_test_sample_crop/'  # prefix path to your images
out_file: 'result.txt'  # path to file you want save your results
